apiVersion: apps/v1
kind: Deployment                 # Type of Kubernetes resource
metadata:
  name: gok8s           # Name of the Kubernetes resource
spec:
  replicas: 3                    # Number of pods to run at any given time
  selector:
    matchLabels:
      app: gok8s        # This deployment applies to any Pods matching the specified label
  template: # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels: # The labels that will be applied to all of the pods in this deployment
        app: gok8s
    spec:
      containers:
        - name: gok8s
          image: nmvuong92/gok8s:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080